"""empty message

Revision ID: d6ef8e0644e4
Revises: 0e55104ba32f
Create Date: 2020-01-13 02:09:47.294587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ef8e0644e4'
down_revision = '0e55104ba32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movie', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movie', 'description')
    # ### end Alembic commands ###
